# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('passwd', models.CharField(max_length=100, verbose_name='口令')),
                ('email', models.CharField(max_length=50, unique=True, verbose_name='邮箱')),
                ('photo', models.CharField(blank=True, max_length=100, null=True, verbose_name='头像')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'db_table': 't_user',
            },
        ),
    ]
