# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 13:05
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('author', models.CharField(max_length=50, verbose_name='作者')),
                ('state', models.IntegerField(choices=[(0, '连载中'), (1, '已完结')], default=0, verbose_name='状态')),
                ('summary', models.CharField(max_length=200, verbose_name='简介')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, verbose_name='正文')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('last_refresh_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='art/images', verbose_name='封面')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 't_art',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '文章分类',
                'verbose_name_plural': '文章分类',
                'db_table': 't_tag',
                'ordering': ['-add_time'],
            },
        ),
        migrations.AddField(
            model_name='art',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='art.Tag', verbose_name='分类'),
        ),
    ]
